// MSXgl | Raw files definitions generated by the Build tool

#define VRAM_SC8_SEG 	3
#define VRAM_SC8_REL 	0x0000
#define VRAM_SC8_ABS 	0x6000
#define VRAM_SC8_SIZE	0x2000

#define PENGUIN_LVM_SEG 	6
#define PENGUIN_LVM_REL 	0x0000
#define PENGUIN_LVM_ABS 	0xC000
#define PENGUIN_LVM_SIZE	0x14CB

#define MM_DEVA_08_BIN_SEG 	7
#define MM_DEVA_08_BIN_REL 	0x0000
#define MM_DEVA_08_BIN_ABS 	0xE000
#define MM_DEVA_08_BIN_SIZE	0x9B17
