// MSXgl | Raw files definitions generated by the Build tool

#define XAA_ZX0_SEG 	3
#define XAA_ZX0_REL 	0x0000
#define XAA_ZX0_ABS 	0x6000
#define XAA_ZX0_SIZE	0x0243

#define XAB_ZX0_SEG 	3
#define XAB_ZX0_REL 	0x0243
#define XAB_ZX0_ABS 	0x6243
#define XAB_ZX0_SIZE	0x0423

#define XAC_ZX0_SEG 	3
#define XAC_ZX0_REL 	0x0666
#define XAC_ZX0_ABS 	0x6666
#define XAC_ZX0_SIZE	0x01F1

#define PALETTE_BIN_SEG 	3
#define PALETTE_BIN_REL 	0x0857
#define PALETTE_BIN_ABS 	0x6857
#define PALETTE_BIN_SIZE	0x0020

#define PENGUIN_LVM_SEG 	6
#define PENGUIN_LVM_REL 	0x0000
#define PENGUIN_LVM_ABS 	0xC000
#define PENGUIN_LVM_SIZE	0x14CB

#define MM_DEVA_08_BIN_SEG 	7
#define MM_DEVA_08_BIN_REL 	0x0000
#define MM_DEVA_08_BIN_ABS 	0xE000
#define MM_DEVA_08_BIN_SIZE	0x9B17
